contact_links:
  - name: Support and general enquiries
    url: https://catma.de/about/contact/
    about: See contact information
  - name: Community chat
    url: https://catma.de/documentation/mattermost/
    about: Join us on Mattermost
